on:
  push:
    branches:
      - "master"

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

name: Deploy package to Github Branch
jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Increase the version number from the package.json
        run: source .github/workflows/increment-tag.sh; increase_packagejson_version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v3
        with:
          node-version: '16.18'
          registry-url: 'https://npm.pkg.github.com'
          # Defaults to the user or organization that owns the workflow file
          scope: '@octocat'
      - name: Install dependencies (using package-lock.json)
        run: npm ci
      - name: Build Lib
        run: npm run build
      - name: Deploy to GPR 🚀
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Increase the version number from the package.json
        run: export NEW_VERSION="${{ env.NEW_VERSION }}" && source .github/workflows/increment-tag.sh; increase_github_tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}